In [2]:
import pandas as pd
import pandas_ta as ta
import numpy as np
import backtesting.test as utils

In [3]:
help(ta.bbands)

Help on function bbands in module pandas_ta.volatility.bbands:

bbands(close, length=None, std=None, ddof=0, mamode=None, talib=None, offset=None, **kwargs)
    Bollinger Bands (BBANDS)

    A popular volatility indicator by John Bollinger.

    Sources:
        https://www.tradingview.com/wiki/Bollinger_Bands_(BB)

    Calculation:
        Default Inputs:
            length=5, std=2, mamode="sma", ddof=0
        EMA = Exponential Moving Average
        SMA = Simple Moving Average
        STDEV = Standard Deviation
        stdev = STDEV(close, length, ddof)
        if "ema":
            MID = EMA(close, length)
        else:
            MID = SMA(close, length)

        LOWER = MID - std * stdev
        UPPER = MID + std * stdev

        BANDWIDTH = 100 * (UPPER - LOWER) / MID
        PERCENT = (close - LOWER) / (UPPER - LOWER)

    Args:
        close (pd.Series): Series of 'close's
        length (int): The short period. Default: 5
        std (int): The long period. Default: 2
        ddof (int): Degrees of Freedom to use. Default: 0
        mamode (str): See ```help(ta.ma)```. Default: 'sma'
        talib (bool): If TA Lib is installed and talib is True, Returns the TA Lib
            version. Default: True
        offset (int): How many periods to offset the result. Default: 0

    Kwargs:
        fillna (value, optional): pd.DataFrame.fillna(value)
        fill_method (value, optional): Type of fill method

    Returns:
        pd.DataFrame: lower, mid, upper, bandwidth, and percent columns.

In [4]:
df = utils.GOOG[2100:]
df.tail()

             Open    High     Low   Close   Volume
2013-02-25  802.3  808.41  790.49  790.77  2303900
2013-02-26  795.0  795.95  784.40  790.13  2202500
2013-02-27  794.8  804.75  791.11  799.78  2026100
2013-02-28  801.1  806.99  801.03  801.20  2265800
2013-03-01  797.8  807.14  796.15  806.19  2175400

In [5]:
x = ta.bbands(df.Close)
x

             BBL_5_2.0  BBM_5_2.0   BBU_5_2.0  BBB_5_2.0  BBP_5_2.0
2012-12-20         NaN        NaN         NaN        NaN        NaN
2012-12-21         NaN        NaN         NaN        NaN        NaN
2012-12-24         NaN        NaN         NaN        NaN        NaN
2012-12-26         NaN        NaN         NaN        NaN        NaN
2012-12-27  700.945424    712.530  724.114576   3.251674   0.230676
2012-12-28  697.941897    708.060  718.178103   2.857979   0.102198
2012-12-31  699.626785    706.410  713.193215   1.920475   0.571500
2013-01-02  693.830551    709.160  724.489449   4.323269   0.959573
2013-01-03  692.928585    712.120  731.311415   5.389938   0.800916
2013-01-04  691.714315    718.456  745.197685   7.444209   0.864861
2013-01-07  703.904919    725.404  746.903081   5.927478   0.717358
2013-01-08  718.558833    730.588  742.617167   3.293010   0.612726
2013-01-09  722.996491    733.562  744.127509   2.880604   0.715702
2013-01-10  731.400971    737.124  742.847029   1.552799   0.880568
2013-01-11  731.355579    737.528  743.700421   1.673813   0.699436
2013-01-14  722.042630    735.228  748.413370   3.586743   0.045784
2013-01-15  717.917179    733.554  749.190821   4.263305   0.224241
2013-01-16  708.633421    728.968  749.302579   5.579005   0.161217
2013-01-17  703.140131    722.936  742.731869   5.476520   0.206605
2013-01-18  700.693832    715.840  730.986168   4.231719   0.125978
2013-01-22  695.839128    711.764  727.688872   4.474762   0.220751
2013-01-23  687.178536    715.078  742.977464   7.803194   0.973522
2013-01-24  680.931897    722.882  764.832103  11.606349   0.873396
2013-01-25  685.262691    731.352  777.441309  12.603865   0.742117
2013-01-28  701.783252    740.596  779.408748  10.481490   0.630550
2013-01-29  741.181133    750.758  760.334867   2.551253   0.652555
2013-01-30  750.699509    753.224  755.748491   0.670316   0.620024
2013-01-31  750.340415    753.520  756.699585   0.843928   0.841240
2013-02-01  739.929212    757.906  775.882788   4.743804   0.992135
2013-02-04  743.072613    759.564  776.055387   4.342330   0.483507
2013-02-05  746.116867    761.976  777.835133   4.162633   0.618670
2013-02-06  750.772640    765.244  779.715360   3.782156   0.670198
2013-02-07  756.909163    768.896  780.882837   3.117934   0.710815
2013-02-08  753.255369    770.850  788.444631   4.564995   0.912626
2013-02-11  760.795882    775.530  790.264118   3.799755   0.733811
2013-02-12  767.297303    778.522  789.746697   2.883591   0.597018
2013-02-13  773.347807    781.060  788.772193   1.974802   0.616698
2013-02-14  778.852633    783.834  788.815367   1.271026   0.900091
2013-02-15  776.422428    785.338  794.253572   2.270506   0.923529
2013-02-19  771.585422    790.224  808.862578   4.717290   0.946010
2013-02-20  776.554032    792.576  808.597968   4.043011   0.496380
2013-02-21  782.363267    795.110  807.856733   3.206282   0.516475
2013-02-22  786.798174    797.488  808.177826   2.680874   0.603931
2013-02-25  785.542489    797.064  808.585511   2.890988   0.226859
2013-02-26  786.658306    793.720  800.781694   1.779392   0.245812
2013-02-27  786.853146    795.184  803.514854   2.095327   0.775842
2013-02-28  786.668267    796.318  805.967733   2.423588   0.752960
2013-03-01  785.157698    797.614  810.070302   3.123391   0.844243

In [7]:
type(df.Close)

AttributeError: 'Series' object has no attribute 's'